// This file is auto-generated by scripts/generate-exports.ts
// Do not edit manually. Run `pnpm db:generate` to regenerate.
// NOTE: This exports from browser.ts (no Node.js runtime deps).
// For the prisma instance, import from 'database/client' instead.

export type {
	AiReport,
	Equipment,
	FailureReport,
	InspectionItem,
	InspectionRecord,
	InspectionValue,
	Invitation,
	Part,
	Photo,
	User,
	VisibleEquipment,
	VisibleFailureReport,
	VisibleInspectionItem,
	VisibleInspectionRecord,
	VisibleInvitation,
	VisiblePart,
	VisibleUser,
} from "./generated/client/browser";
export {
	$Enums,
	InspectionInputType,
	InspectionStatus,
	InvitationStatus,
	Prisma,
	UserRole,
} from "./generated/client/browser";
